# Generated by Django 5.0.2 on 2025-03-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_app', '0002_add_sender_name_to_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_name',
        ),
    ]
