# Generated by Django 5.0.2 on 2025-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_app', '0003_remove_message_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
