# Generated by Django 5.0.2 on 2025-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_app', '0004_add_sender_name_to_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP-адрес')),
                ('reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до')),
                ('is_permanent', models.BooleanField(default=True, verbose_name='Постоянная блокировка')),
            ],
            options={
                'verbose_name': 'Заблокированный IP',
                'verbose_name_plural': 'Заблокированные IP',
            },
        ),
    ]
